apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  labels:
    app: docker
spec:
  replicas: "{{$.iios.app.replicas}}"
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: "ignitial/docker:{{$.iios.app.version}}"
        imagePullPolicy: "{{$.iios.app.imagePullPolicy}}"
        volumeMounts:
        - name: config-volume
          mountPath: /opt/docker/server/config/generated
        ports: "{{$.iios.app.ports}}"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: docker-config

---
apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  selector:
    app: docker
  ports:
  - name: http
    port: "{{$.iios.app.ports[0].containerPort}}"
    targetPort: "{{$.iios.app.ports[0].containerPort}}"
